name: "Release"
on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: Keep dist up-to-date
      run: |
        npm i
        npm run build
        npm run pack
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/index.js
        git commit -m "chore: publish dist" || echo "nothing to commit"
        git push origin master
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: Test Action
      uses: ./
      with:
        SECRETS: |
          ^FOO$
          ^GITHUB_.*
        REPOSITORIES: |
          ^nathanklick/SnowWhite.NET$
        DRY_RUN: true
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN_NO_SCOPES }}
        NEW_SECRET_PREFIX: "TEST_ACTION_"
      env:
        FOO: ${{github.run_id}}
        FOOBAR: BAZ
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 19.0.5
        extra_plugins: |
          "@semantic-release/commit-analyzer"
          "@semantic-release/release-notes-generator"
          "@semantic-release/git"
          "@semantic-release/github"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
